#ifndef _TREE_TAGS_H_
#define _TREE_TAGS_H

#define AST_TAG_TYPE_KEY "type"

#define AST_TAG_PROGRAM "program"
#define AST_TAG_STMTS "stmts"
#define AST_TAG_STMT "stmt"
#define AST_TAG_EXPR "expr"
#define AST_TAG_TERM "term"
#define AST_TAG_ASSIGNEXPR "assignexpr"
#define AST_TAG_PRIMARY "primary"
#define AST_TAG_LVALUE "lvalue"
#define AST_TAG_MEMBER "member"
#define AST_TAG_CALL "call"
#define AST_TAG_CALLSUFFIX "callsuffix"
#define AST_TAG_NORMCALL "normcall"
#define AST_TAG_METHODCALL "methodcall"
#define AST_TAG_METHODCALL_ID "methodcall_id"
#define AST_TAG_ELIST "elist"
#define AST_TAG_COMMA_EXPRS "comma_exprs"
#define AST_TAG_COMMA_EXPR "comma_expr"
#define AST_TAG_OBJECTDEF "objectdef"
#define AST_TAG_OBJECTDEF_VAL "objectdef_val"
#define AST_TAG_INDEXED "indexed"
#define AST_TAG_COMMA_INDEXEDELEMS "comma_indexedelems"
#define AST_TAG_COMMA_INDEXEDELEM "comma_indexedelem"
#define AST_TAG_INDEXEDELEM "indexedelem"
#define AST_TAG_BLOCK "block"
#define AST_TAG_FUNCDEF "funcdef"
#define AST_TAG_funcblock "funcblock"
#define AST_TAG_FUNC_ID "func_id"
#define AST_TAG_CONST "const"
#define AST_TAG_CONST_NUMBER "const_number"
#define AST_TAG_CONST_STRING "const_string"
#define AST_TAG_CONST_NIL "const_nil"
#define AST_TAG_CONST_TRUE "const_true"
#define AST_TAG_CONST_FALSE "const_false"
#define AST_TAG_IDLIST "idlist"
#define AST_TAG_COMMA_IDS "comma_ids"
#define AST_TAG_COMMA_ID "comma_id"
#define AST_TAG_IFSTMT "ifstmt"
#define AST_TAG_IFCOND "ifcond"
#define AST_TAG_WHILESTMT "whilestmt"
#define AST_TAG_WHILECOND "whilecond"
#define AST_TAG_FORSTMT "forstmt"
#define AST_TAG_FORPREFIX "forprefix"
#define AST_TAG_RETURNSTMT "returnstmt"
#define AST_TAG_RETURNVALUE "returnvalue"

#endif